# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eac5f819bf4e30943c7b65a090b7a67008d02d220a8ae843f93eed3a28655e0aec7238925d8ee427dd162d6ff55e511213710c401f3930cbe9ec662e56f2a7b

test:
  secret_key_base: 0cfcc63ab6652d3517e812b57b3e7328787738db5f3f10e9225b901c8d6042103b6093f7fbc9bc2627f35522bdcf452b0f25313830f5b35282eb304909e62068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
